Makes the script crash on unhandled rejections instead of silently ignoring them
See https://github.com/facebook/jest/issues/5311#issuecomment-362752169

✗ Errored » Asynchronous Error
      in Integration tests
      in test/integration-test.js
/home/macbre/github/phantomas/test/integration-test.js:19
	throw err;
	^

Error: Protocol error (Performance.getMetrics): Session closed. Most likely the page has been closed.
    at CDPSession.send (/home/macbre/github/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:195:35)
    at Page.metrics (/home/macbre/github/phantomas/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:699:45)
    at /home/macbre/github/phantomas/lib/browser.js:266:37
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)